From mysql:8.0.26
command: --default-authentication-plugin=mysql_native_password
restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Stefa9@2020
            MYSQL_USER: sysadm
            MYSQL_PASSWORD: Stefa9@2020
            MYSQL_DATABASE: db_vendas