name: DemoNewCD.NET

on:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, world!

  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'https://github.com/AJKFreitas/SistemaVendas'
    needs: build  
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev!

  deploy-hml:
    runs-on: ubuntu-latest
    environment: 
      name: hml
      url: 'https://github.com/AJKFreitas/SistemaVendas'
    needs: deploy-dev  
    steps:
      - name: Run a one-line script
        run: echo Deploy HML!
        
  deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: hml
      url: 'https://github.com/AJKFreitas/SistemaVendas'
    needs: deploy-hml  
    steps:
      - name: Run a one-line script
        run: echo Deploy Prod!
