name: Input example

on:
  workflow_dispatch:
    inputs:
      evironment:
        description: 'The evironment to deploy to'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.evironment}} evironment"
